### ISSUE TITLE
Debian: either split components or remove non-free and contrib all together

### ISSUE THREAD

**Issue by dirk-thomas** [osrf/multiarch-docker-image-generation#22]
In order for ros-infrastructure/ros_buildfarm#530 to work [the script](https://github.com/osrf/multiarch-docker-image-generation/blob/cad9efbfbfbb24c3190e03de2803fa72d7093405/build-image.sh#L93-L98) needs to:

* either generate separate `deb` lines for `main`, `non-free`, and `contrib` or
* remove `non-free` and `contrib` (aligning what other Debian images use)

**Comment by tfoote** [comment]
If reformatting this will make our script work that's good. Though we can't always rely on upstream never doing this. We should probably discuss removing them in #4
