### ISSUE TITLE
Push new rebuilds with newer version of dpkg installed

### ISSUE THREAD

**Issue by tfoote** [osrf/multiarch-docker-image-generation#26]
There's a new version of dpkg available for trusty which will resolve https://github.com/ros-infrastructure/catkin_pkg/issues/227 

And we might as well refresh all the other images while we're at it to keep them up to date with the amd64 images from docker. It will keep our updates/installation requirements lower at runtime.

**Comment by nuclearsandwich** [comment]
New images have been pushed to the following tags

* osrf/debian_arm64:jessie
* osrf/debian_armhf:jessie
* osrf/debian_arm64:stretch
* osrf/debian_armhf:stretch
* osrf/ubuntu_i386:artful
* osrf/ubuntu_i386:trusty
* osrf/ubuntu_armhf:trusty
* osrf/ubuntu_armhf:xenial
* osrf/ubuntu_arm64:xenial
* osrf/ubuntu_i386:xenial
* osrf/ubuntu_armhf:bionic
* osrf/ubuntu_arm64:bionic
* osrf/ubuntu_i386:bionic

In addition to the usual smoke testing I installed python3-catkin-pkg-modules on both trusty images successfully.

**Comment by nuclearsandwich** [comment]
Since images are rebuilt I'll close this for now. I won't yet make the presumption that the issues necessitating rebuilds are resolved.
